txt="im from codeyad ii  "
# print(txt.capitalize())
# print(txt.casefold)
# print(txt.count(" "))
# print(txt.count("m"))
# print(txt.find("im"))
# print(txt.index("f"))
# print(txt.format("amir","amiri"))
# print(txt.strip())
# print(txt.title())
# print(txt.upper())
# print(txt.lower())
